name: Docker Image CD

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # SSH 접속을 위한 SSH 키 설정
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 원격 서버의 SSH 호스트 키를 저장하여 SSH 연결 시 신뢰성을 등록하는 과정
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: application.yml 생성
        run: |
          mkdir -p src/main/resources
          touch src/main/resources/application.yml
          echo "${{ secrets.ENV }}" > src/main/resources/application.yml

      # 서버 이미지 빌드 및 태그 지정
      - name: Build and tag Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/baekjoon-testcase:${{ github.sha }} ./
          docker tag ${{ secrets.DOCKER_USERNAME }}/baekjoon-testcase:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/baekjoon-testcase:latest

      # 서버 이미지 푸시 (Docker Hub 또는 다른 레지스트리)
      - name: Push server image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/baekjoon-testcase:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/baekjoon-testcase:latest

      # Docker Compose로 전체 애플리케이션 빌드 및 실행 (테스트)
      - name: Run Docker Compose for testing
        run: |
          docker run -d ${{ secrets.DOCKER_USERNAME }}/baekjoon-testcase:latest
        continue-on-error: false

      # 서버에서 파일을 최신화 하고, 배포 스크립트를 통해 실제 배포 진행
      - name: Deploy with Docker Compose on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} " \
            sudo mkdir -p /home/${{ secrets.SSH_USER }}/baekjoon-testcase && \
            cd /home/${{ secrets.SSH_USER }}/baekjoon-testcase && \
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/baekjoon-testcase:latest && \
            sudo ./deploy.sh && \
            sudo docker system prune -af"
